### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by gari30**
Add important things to the README.

### CODE REVIEW

**Comment by lrf141** [comment]
@gari30 
you have no sense of humor, bring me back some new ideas haha

**Comment by lrf141** [comment]
@gari30
why did you added blank line??
you can't see this one????

**Comment by gari30** [comment]
@lrf141 
The file must end with a newline code.
It is written to this IEEE.
[Overview](http://hiroakiuno.hatenablog.com/entry/20070409/p1).

**Comment by lrf141** [comment]
@gari30 It is not worth reading.

**Pull request closed without merging**
